from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class TalkMessage(BaseModel):
    role: str = Field(..., description="The role of the message sender (user or assistant).")
    content: str = Field(..., description="The textual content of the message.")

class TalkRequest(BaseModel):
    message: str = Field(..., max_length=1000, description="The current message from the user.")
    conversation: List[TalkMessage] = Field(default_factory=list, description="Short-term conversation history.")
    emotion_profile: Optional[Dict[str, Any]] = Field(None, description="The emotional profile generated by the CNN.")
    user_intent: Optional[str] = Field("comfort", description="The user's stated intent (e.g., vent, advice).")

class TalkResponse(BaseModel):
    success: bool = True
    message: str = Field(..., description="The conversational response text.")
    tone: str = Field(..., description="The tone applied to the response.")
    should_suggest_music: bool = Field(False, description="Whether music should be suggested.")
    music_reason: str = Field("", description="The reason for the music suggestion, if applicable.")
    safety_level: str = Field("normal", description="Safety level: normal, caution, urgent")

class ErrorResponse(BaseModel):
    success: bool = False
    error: Dict[str, str]
